server:
  port: 8081

application:
  regex:
    email: '^[a-zA-Z0-9]+[\w\-\.]*@[a-zA-Z0-9]+[\w\-]*[\.]cl$'
    password: '^(?=.*[a-z])(?=.*[A-Z])(?=.*\d)(?=.*[@$!%*?&\.\-\_])[A-Za-z\d@$!%?&\.\-\_]{8,20}$'
  jwt:
    secret: 9aeb8f4e-5c43-4764-a802-cfbc9be49db5
    expire: 300000

spring:
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password: 1234
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create-drop
  h2:
    console:
      enabled: true
      
logging:
  level:
    org:
      hibernate:
        sql: debug